### ISSUE TITLE
sorry, please help

### ISSUE THREAD

**Issue by shaun-lloyd** [Holyoke/Gamepad-React#1]
hello,
I'm obviously newbie to react. Can you please tell me simple command i need to run to get Gamepad-React server running. Totally not a bug, i just need a little help i seriously can't find a single tutorial on how to get this thing running. I really love the pattern you have setup and just want to get into the code.

Really appreciate a little help :)

**Comment by shaun-lloyd** [comment]
I've tried:

npm install
npm install webpack-dev-server

npm run

just tells me about webpack

i run npm run webpack. Something happens. 

But what cmd do i run to just start the server ?

**Comment by JasonEb** [comment]
There should be no need to run a server - just open the `index.html`. Webpack-dev-server is only for hot reloading the app whenever the code is saved. So no need for a server command!

**Comment by shaun-lloyd** [comment]
Thank you so much ! 

Figured i was being an idiot

You really saved my frustration. Have a great day !
